---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast-publisher
  template:
    metadata:
      labels:
        app: hazelcast-publisher
    spec:
      containers:
        - name: hazelcast-publisher
          image: publisher:0.1.0
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-publisher
spec:
  type: ClusterIP
  selector:
    app: hazelcast-publisher
  ports:
  - name: app
    port: 8080
  - name: grpc
    port: 9090
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: publisher-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: publisher.hazelcast
      http:
        paths:
          - path: /.*
            backend:
              serviceName: hazelcast-publisher
              servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: publisher-grpc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
    - host: publisher.grpc.hazelcast
      http:
        paths:
          - backend:
              serviceName: hazelcast-publisher
              servicePort: 9090
  tls:
    - secretName: tls-secret
      hosts:
        - publisher.grpc.hazelcast